# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost
# when pyuic5 is run again. Do not edit this file unless you know what you are doing.

from PySide6 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.someButton = QtWidgets.QPushButton(self.centralwidget)
        self.someButton.setGeometry(QtCore.QRect(150, 200, 100, 30))
        self.someButton.setObjectName("someButton")

        self.someTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.someTextEdit.setGeometry(QtCore.QRect(100, 50, 200, 100))
        self.someTextEdit.setObjectName("someTextEdit")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MyApp"))
        self.someButton.setText(_translate("MainWindow", "Click Me"))
